r_heaven_ski_index:
    pattern:  /
    defaults: { _controller: RHeavenSkiBundle:Default:index }


r_heaven_ski_homepage:
    pattern:  /ski
    defaults: { _controller: RHeavenSkiBundle:Default:home }

RHeavenSkiBundle_materiel:
    resource: "@RHeavenSkiBundle/Resources/config/routing/materiel.yml"
    prefix:   /materiel

r_heaven_ski_person:
    pattern:  /ski/person
    defaults: { _controller: RHeavenSkiBundle:Default:person }

r_heaven_ski_options:
    pattern:  /ski/options
    defaults: { _controller: RHeavenSkiBundle:Default:options }

r_heaven_ski_paiement:
    pattern:  /ski/paiement
    defaults: { _controller: RHeavenSkiBundle:Default:paiement }

r_heaven_ski_print_pdf:
    pattern:  /ski/print/pdf
    defaults: { _controller: RHeavenSkiBundle:Default:pdf }

r_heaven_ski_admin:
    pattern:  /admin
    defaults: { _controller: RHeavenSkiBundle:Admin:status }

r_heaven_ski_admin_show:
    pattern:  /admin/show/{id}
    defaults: { _controller: RHeavenSkiBundle:Admin:show }

r_heaven_ski_admin_print:
    pattern:  /admin/print/{id}
    defaults: { _controller: RHeavenSkiBundle:Admin:pdf }

r_heaven_ski_admin_calidation:
    pattern:  /admin/validation/{id}/{type}
    defaults: { _controller: RHeavenSkiBundle:Admin:validation }